/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab3;

import javax.swing.JOptionPane;

/**
 *
 * @author huyen
 */
public class TroChoiOSo extends javax.swing.JFrame {

    /**
     * Creates new form TroChoiOSo
     */
    String hoten;
    boolean check;
    int vitriTrong;
    int vitriHoanVi;
    String []arr;//chua so tuong ung cac button
    void ganGiaTriMangVaoNut(){
        b1.setText(arr[0]);
        b2.setText(arr[1]);
        b3.setText(arr[2]);
        b4.setText(arr[3]);
        b5.setText(arr[4]);
        b6.setText(arr[5]);
        b7.setText(arr[6]);
        b8.setText(arr[7]);
        b9.setText(arr[8]);
        b10.setText(arr[9]);
        b11.setText(arr[10]);
        b12.setText(arr[11]);
        b13.setText(arr[12]);
        b14.setText(arr[13]);
        b15.setText(arr[14]);
        b0.setText(arr[15]);  
    }
    void ganGiaTri(){
        arr[0]= b1.getText();
        arr[1]= b2.getText();
        arr[2]= b3.getText();
        arr[3]= b4.getText();
        arr[4]= b5.getText();
        arr[5]= b6.getText();
        arr[6]= b7.getText();
        arr[7]= b8.getText();
        arr[8]= b9.getText();
        arr[9]= b10.getText();
        arr[10]= b11.getText();
        arr[11]= b12.getText();
        arr[12]= b13.getText();
        arr[13]= b14.getText();
        arr[14]= b15.getText();
        arr[15]= b0.getText();     
    }
    public TroChoiOSo() {
        hoten= JOptionPane.showInputDialog("Nhap ten cua ban:");
        initComponents();
        this.setTitle(hoten);
        check=false;
        vitriTrong=15;
        arr= new String [16];
        ganGiaTri();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        b1.setText("1");
        jPanel1.add(b1);

        b2.setText("5");
        jPanel1.add(b2);

        b3.setText("8");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);

        b4.setText("9");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);

        b5.setText("4");
        jPanel1.add(b5);

        b6.setText("12");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);

        b7.setText("15");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);

        b8.setText("6");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);

        b9.setText("2");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);

        b10.setText("11");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10);

        b11.setText("3");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11);

        b12.setText("10");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12);

        b13.setText("7");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel1.add(b13);

        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel1.add(b14);

        b15.setText("13");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        jPanel1.add(b15);

        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Trò Chơi Ô Số");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Bắt đầu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[9];  
        arr[9]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=9;
    }//GEN-LAST:event_b10ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[13];  
        arr[13]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=13;
    }//GEN-LAST:event_b14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (check==false){
            check=true;//trang thai dang choi
            jButton1.setText("Dung choi");
        }else{
            //hien thi ket qua, dung choi
            int i=JOptionPane.showConfirmDialog
                  (this, "Ban co muon ket thuc?");
            if(i==0){
                //kiem tra
                if(arr[0].equals("1") &&arr[1].equals("2")&& arr[15].equals("")){
                    JOptionPane.showMessageDialog(this, "Ban da thang");
                }else{
                    JOptionPane.showMessageDialog(this, "Game Over");
                }
                jButton1.setText("Bat dau");
                check=false;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[14];  
        arr[14]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=14;
                
    }//GEN-LAST:event_b15ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[12];  
        arr[12]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=12;
    }//GEN-LAST:event_b13ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[11];  
        arr[11]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=11;
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[10];  
        arr[10]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=10;
    }//GEN-LAST:event_b11ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[8];  
        arr[8]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=8;
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[7];  
        arr[7]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=7;
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[6];  
        arr[6]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=6;
    }//GEN-LAST:event_b7ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        String trungGian=arr[15];  
        arr[15]=arr[vitriTrong];
        arr[vitriTrong] =trungGian;
        ganGiaTriMangVaoNut();
        ganGiaTri();
        vitriTrong=15;
    }//GEN-LAST:event_b0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TroChoiOSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TroChoiOSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TroChoiOSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TroChoiOSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TroChoiOSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
