/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2;

/**
 *
 * @author huyen
 */
public class FrmCalculator extends javax.swing.JFrame {

    /**
     * Creates new form FrmCalculator
     */
    double ketQua;
    String dau;
    public FrmCalculator() {
        initComponents();
        ketQua=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hienThi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bChia = new javax.swing.JButton();
        bBac2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bNhan = new javax.swing.JButton();
        bPhanTram = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bTru = new javax.swing.JButton();
        bNghichDao = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bDoiDau = new javax.swing.JButton();
        bXoa = new javax.swing.JButton();
        bCong = new javax.swing.JButton();
        bBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hienThi.setText("0");

        jPanel1.setLayout(new java.awt.GridLayout(4, 5));

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);

        b3.setText("3");
        jPanel1.add(b3);

        bChia.setText("/");
        bChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChiaActionPerformed(evt);
            }
        });
        jPanel1.add(bChia);

        bBac2.setText("sqrt");
        bBac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBac2ActionPerformed(evt);
            }
        });
        jPanel1.add(bBac2);

        b4.setText("4");
        jPanel1.add(b4);

        b5.setText("5");
        jPanel1.add(b5);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);

        bNhan.setText("x");
        bNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNhanActionPerformed(evt);
            }
        });
        jPanel1.add(bNhan);

        bPhanTram.setText("%");
        jPanel1.add(bPhanTram);

        b7.setText("7");
        jPanel1.add(b7);

        b8.setText("8");
        jPanel1.add(b8);

        b9.setText("9");
        jPanel1.add(b9);

        bTru.setText("-");
        bTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTruActionPerformed(evt);
            }
        });
        jPanel1.add(bTru);

        bNghichDao.setText("1/x");
        jPanel1.add(bNghichDao);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);

        bDoiDau.setText("+/-");
        jPanel1.add(bDoiDau);

        bXoa.setText("C");
        bXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXoaActionPerformed(evt);
            }
        });
        jPanel1.add(bXoa);

        bCong.setText("+");
        bCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCongActionPerformed(evt);
            }
        });
        jPanel1.add(bCong);

        bBang.setText("=");
        bBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBangActionPerformed(evt);
            }
        });
        jPanel1.add(bBang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        String s= hienThi.getText();
        if (s.equals("0"))
             hienThi.setText("2");
        else
            hienThi.setText(s+"2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void bTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTruActionPerformed
        // TODO add your handling code here:
        ketQua= Double.parseDouble(hienThi.getText());
        hienThi.setText("0");
        dau="-";
    }//GEN-LAST:event_bTruActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String s= hienThi.getText();
        if (s.equals("0"))
             hienThi.setText("1");
        else
            hienThi.setText(s+"1");
    }//GEN-LAST:event_b1ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        String s= hienThi.getText();
        if (!s.equals("0"))
            hienThi.setText(s+"0");        
    }//GEN-LAST:event_b0ActionPerformed

    private void bCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCongActionPerformed
        // TODO add your handling code here:
        ketQua= Double.parseDouble(hienThi.getText());
        hienThi.setText("0");
        dau="+";
    }//GEN-LAST:event_bCongActionPerformed

    private void bBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBangActionPerformed
        // TODO add your handling code here:
        if (dau.equals("+")){
            ketQua=ketQua+ Double.parseDouble(hienThi.getText());
        }
        if (dau.equals("-")){
            ketQua=ketQua- Double.parseDouble(hienThi.getText());
        }
        if (dau.equals("x")){
            ketQua=ketQua* Double.parseDouble(hienThi.getText());
        }
        if (dau.equals("/")){
            ketQua=ketQua/ Double.parseDouble(hienThi.getText());
        }
        hienThi.setText(ketQua+"");
    }//GEN-LAST:event_bBangActionPerformed

    private void bNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNhanActionPerformed
        // TODO add your handling code here:
        ketQua= Double.parseDouble(hienThi.getText());
        hienThi.setText("0");
        dau="x";
    }//GEN-LAST:event_bNhanActionPerformed

    private void bChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChiaActionPerformed
        // TODO add your handling code here:
        ketQua= Double.parseDouble(hienThi.getText());
        hienThi.setText("0");
        dau="/";
    }//GEN-LAST:event_bChiaActionPerformed

    private void bXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXoaActionPerformed
        // TODO add your handling code here:
        String s= hienThi.getText();
        if(s.length()==1){
            hienThi.setText("0");
        }else{
        String sub= s.substring(0, s.length()-1);
        hienThi.setText(sub);
        }
    }//GEN-LAST:event_bXoaActionPerformed

    private void bBac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBac2ActionPerformed
        // TODO add your handling code here:
        ketQua=Double.parseDouble(hienThi.getText());
        hienThi.setText(Math.sqrt(ketQua)+"");
    }//GEN-LAST:event_bBac2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bBac2;
    private javax.swing.JButton bBang;
    private javax.swing.JButton bChia;
    private javax.swing.JButton bCong;
    private javax.swing.JButton bDoiDau;
    private javax.swing.JButton bNghichDao;
    private javax.swing.JButton bNhan;
    private javax.swing.JButton bPhanTram;
    private javax.swing.JButton bTru;
    private javax.swing.JButton bXoa;
    private javax.swing.JLabel hienThi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
